print("hi")
import numpy as np
a = np.arange(15).reshape(3,5)
print(a)
print(a.shape)
print(a.ndim)
print(a.itemsize)
print(a.dtype.name)
print(a.size)
print(type(a))
b = np.array([1,3,5])
print(b)
print(b.shape)
print(b.ndim)
print(type(b))